config/routes.rb
Sample::Application.routes.draw do

	devise_for :users
	get "home/index"
	root :to => "home#index"
	resources :bookings, :customers, :products, :billings, :cashes, :expenses, :users

	resources :rooms do
		resources :bookings, :module => :rooms
	end

	resources :bookings do
		get 'choose_classification', on: :new
		get 'billing', on: :member
		post 'billing' => "bookings#create_billing", :as => "billings"
		resources :orders, :module => :bookings
	end

	resources :classifications do
		resources :pricings, :module => :classifications
		collection { post :import }
	end

	resource :user, only: [:edit] do
		collection do
			patch 'update_password'
		end
	end
end

app/models/classification.rb
class Classification < ActiveRecord::Base
	has_many :pricings
	has_many :rooms
	def self.to_csv(options = {})
		options[:col_sep] = ";"
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |product|
				csv << product.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, {headers: true, :col_sep=>";"}) do |row|
			classification = Classification.find_or_initialize_by(row.to_hash)
			begin
				classification.save 
			rescue ActiveRecord::StatementInvalid
				# registro já existe
			end
		end
	end
end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
  belongs_to :classification

  def to_s
  	 self.amount + number_to_currency(self.price)
  end
end

app/controllers/classifications/pricings_controller.rb
class Classifications::PricingsController < ApplicationController
	before_action :set_classification
	load_and_authorize_resource param_method: :pricing_params

	def index
		@pricings = @classification.pricings.paginate(:page=>params[:page])
	end

	def new
		@pricing = @classification.pricings.build
	end

	def create
		@pricing = @classification.pricings.build(pricing_params)
		if @pricing.save
			flash[:notice] = "Preço cadastrado com sucesso"
		end
	end

	def edit
		@pricing = @classification.pricings.find(params[:id])
	end

	def update
		@pricing = @classification.pricings.find(params[:id])
		@pricing.attributes = pricing_params
		if @pricing.save
			flash[:notice] = "Preço alterado com sucesso"
		end
	end

	def destroy
		@pricing = @classification.pricings.find(params[:id])
		if @pricing.destroy
			flash[:notice] = "Removido com sucesso"
		end
	end

	private
	def set_classification
		@classification = Classification.find(params[:classification_id])
	end

	def pricing_params
		pricing_params = params.require(:pricing).permit(:amount, :price)
		pricing_params[:price] = pricing_params[:price].to_number 
		pricing_params
	end
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
	load_and_authorize_resource param_method: :classification_params
	before_filter :set_classification, only: [:edit, :update, :show, :destroy]

	def index
		@classifications = Classification.paginate(:page=>params[:page])
		respond_to do |format|
			format.html 
			format.csv { send_data Classification.all.to_csv }
		end
	end

	def import
		Classification.import(params[:file])
		redirect_to classifications_path
	end

	def new
		@classification = Classification.new
	end

	def create
		@classification = Classification.new(classification_params)
		if @classification.save
			flash[:notice] = "Cadastrado com sucesso"
		end
	end

	def edit
	end

	def update
		if @classification.update_attributes(classification_params)
			flash[:notice] = "Atualizado com sucesso"
		end
	end

	def show
	end

	def destroy
		if @classification.destroy
			flash[:notice] = "Removido com sucesso"
		end
	end

	private
	def set_classification
		@classification = Classification.find(params[:id])
	end

	def classification_params
		params.require(:classification).permit(:name, :description)
	end
end

app/helpers/classifications/pricings_helper.rb
module Classifications::PricingsHelper
	def get_price(model)
		price_range_text = "#{model.amount} - #{number_to_currency(model.price)}" 
		price_range_text
	end
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/classifications/pricings/_form.html.erb
<%= simple_form_for [@classification, @pricing], :remote => true do |f| %>
	<div class="form-group">
		<%= f.input :amount, :input_html=>{:class=>"form-control"} %>
	</div>
	<div class="form-group">
		<label>Preço</label>
		<div class="input-group">
			<span class="input-group-addon">R$</span>
			<%= f.input :price, as: :currency, :label=> false, :input_html=>{value: number_with_precision(f.object.price, precision: 2), :class=>"form-control"} %>
		</div>
	</div>
	<%= button_tag(:type => :submit, :class=>'btn btn-success') do %>
		<i class="icon-save"></i> Salvar
	<% end %>
<% end %>
<script type="text/javascript">
	
$(document).ready(function() {
  $("input[type=text].currency").setMask('decimal');
});
</script>

app/views/classifications/pricings/_pricing_row.html.erb
<td><%= pricing.amount %></td>
<td><%= number_to_currency(pricing.price) %></td>
<td>
	<div class="text-right">
		
		<%= link_to edit_classification_pricing_path(@classification, pricing), remote: true, :class => 'btn btn-success' do %>
		<i class="icon-edit"></i> Editar
		<% end %>

		<%= link_to [@classification,pricing], method: :delete, data: {confirm: "deseja realmente remover?"}, :remote => true, :class=>'removable btn btn-danger' do %>
		<i class="icon-trash"></i> Remover
		<% end %>
	</div>
</td>

app/views/classifications/pricings/create.js.erb
bootbox.hideAll();
$(".notice").html("");
$(".notice").removeClass("alert-info");
$(".notice").show();
$(".notice").addClass("alert alert-success")
$(".notice").html("<%= flash[:notice] %>");
$("table tbody").append("<tr id='pricing-row-<%= @pricing.id%>'><%= escape_javascript(render 'pricing_row', :pricing=> @pricing) %></tr>");

app/views/classifications/pricings/destroy.js.erb
$('.removable').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  
$(".notice").html("");
$(".notice").removeClass("alert-success");
$(".notice").show();
$(".notice").addClass("alert alert-info")
$(".notice").html("<%= flash[:notice] %>")

app/views/classifications/pricings/edit.js.erb
bootbox.dialog({
	message: "<%= escape_javascript(render 'form') %>"
});

app/views/classifications/pricings/index.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>
    <div class='row'>
      <div class='col-sm-12'>
        <div class='page-header'>
          <h1 class='pull-left'>
            <i class='icon-list'></i>
            <span>Preços do Tipo de Quarto: <%= @classification.name %></span>
          </h1>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class='col-sm-12'>

    <div class="notice alert alert-dismissable" style="display:none"></div>
    <div class="box bordered-box green-border" style="margin-bottom:0;">
      <div class="box-header blue-background">
        <div class="title">
      		<i class="icon-money"></i> Preços
        	</div>
        <div class="actions">
          <%= link_to new_classification_pricing_path(@classification), :remote =>true, :class=>'btn btn-success' do %>
            <i class="icon-plus"></i> Cadastrar novo preço
          <% end %>

        </div>
      </div>
      <div class="box-content box-no-padding" style="margin-bottom:0;">
        <div class="responsive-table">
          <table class="table table-striped" style="margin-bottom:0;">
            <thead>
              <tr>
                <th>Quantidade de Pessoas</th>
                <th>Preço</th>
                <th></th>
              </tr>
            </thead>

              
            <tbody>
              <% @pricings.each do |pricing| %>
                <tr id="pricing-row-<%= pricing.id %>">
                  <%= render 'pricing_row', :pricing => pricing %>
                </tr>
              <% end %>
            </tbody>
          </table>
          
        </div>
         <%= will_paginate @pricings, renderer: BootstrapPagination::Rails %>
      </div>

    </div>

  </div>
</div>

app/views/classifications/pricings/new.js.erb
bootbox.dialog({
	message: "<%= escape_javascript(render 'form') %>"
});

app/views/classifications/pricings/update.js.erb
bootbox.hideAll();
$(".notice").html("")
$(".notice").addClass("alert alert-success")
$(".notice").show();
$(".notice").html("<%= flash[:notice] %>");
$("tr#pricing-row-<%= @pricing.id%>").html("<%= escape_javascript(render 'pricing_row', :pricing=> @pricing) %>");