config/routes.rb
Sample::Application.routes.draw do

	devise_for :users
	get "home/index"
	root :to => "home#index"
	resources :bookings, :customers, :products, :billings, :cashes, :expenses, :users

	resources :rooms do
		resources :bookings, :module => :rooms
	end

	resources :bookings do
		get 'choose_classification', on: :new
		get 'billing', on: :member
		post 'billing' => "bookings#create_billing", :as => "billings"
		resources :orders, :module => :bookings
	end

	resources :classifications do
		resources :pricings, :module => :classifications
		collection { post :import }
	end

	resource :user, only: [:edit] do
		collection do
			patch 'update_password'
		end
	end
end

app/models/classification.rb
class Classification < ActiveRecord::Base
	has_many :pricings
	has_many :rooms
	def self.to_csv(options = {})
		options[:col_sep] = ";"
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |product|
				csv << product.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, {headers: true, :col_sep=>";"}) do |row|
			classification = Classification.find_or_initialize_by(row.to_hash)
			begin
				classification.save 
			rescue ActiveRecord::StatementInvalid
				# registro já existe
			end
		end
	end
end

app/controllers/classifications/pricings_controller.rb
class Classifications::PricingsController < ApplicationController
	before_action :set_classification
	load_and_authorize_resource param_method: :pricing_params

	def index
		@pricings = @classification.pricings.paginate(:page=>params[:page])
	end

	def new
		@pricing = @classification.pricings.build
	end

	def create
		@pricing = @classification.pricings.build(pricing_params)
		if @pricing.save
			flash[:notice] = "Preço cadastrado com sucesso"
		end
	end

	def edit
		@pricing = @classification.pricings.find(params[:id])
	end

	def update
		@pricing = @classification.pricings.find(params[:id])
		@pricing.attributes = pricing_params
		if @pricing.save
			flash[:notice] = "Preço alterado com sucesso"
		end
	end

	def destroy
		@pricing = @classification.pricings.find(params[:id])
		if @pricing.destroy
			flash[:notice] = "Removido com sucesso"
		end
	end

	private
	def set_classification
		@classification = Classification.find(params[:classification_id])
	end

	def pricing_params
		pricing_params = params.require(:pricing).permit(:amount, :price)
		pricing_params[:price] = pricing_params[:price].to_number 
		pricing_params
	end
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
	load_and_authorize_resource param_method: :classification_params
	before_filter :set_classification, only: [:edit, :update, :show, :destroy]

	def index
		@classifications = Classification.paginate(:page=>params[:page])
		respond_to do |format|
			format.html 
			format.csv { send_data Classification.all.to_csv }
		end
	end

	def import
		Classification.import(params[:file])
		redirect_to classifications_path
	end

	def new
		@classification = Classification.new
	end

	def create
		@classification = Classification.new(classification_params)
		if @classification.save
			flash[:notice] = "Cadastrado com sucesso"
		end
	end

	def edit
	end

	def update
		if @classification.update_attributes(classification_params)
			flash[:notice] = "Atualizado com sucesso"
		end
	end

	def show
	end

	def destroy
		if @classification.destroy
			flash[:notice] = "Removido com sucesso"
		end
	end

	private
	def set_classification
		@classification = Classification.find(params[:id])
	end

	def classification_params
		params.require(:classification).permit(:name, :description)
	end
end

app/helpers/classifications/pricings_helper.rb
module Classifications::PricingsHelper
	def get_price(model)
		price_range_text = "#{model.amount} - #{number_to_currency(model.price)}" 
		price_range_text
	end
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/classifications/_classification_row.html.erb
<td><%= classification.name %></td>
<td><%= classification.description %></td>
<td>
	<div class="text-right">
		
		<%= link_to edit_classification_path(classification), remote: true, :class => 'btn btn-success' do %>
		<i class="icon-edit"></i> Editar
		<% end %>
		<%= link_to classification, remote: true, :class => 'btn btn-danger', :method => :delete, :data=>{:confirm=>"Deseja realmente remover essa classificação"} do %>
		<i class="icon-trash"></i> Remover
		<% end %>
		<%= link_to classification_pricings_path(classification), :class => 'btn btn-success' do %>
		<i class="icon-money"></i> Preços
		<% end %>
	</div>

</td>

app/views/classifications/_form.html.erb
<%= simple_form_for @classification, :remote=>true, :html=>{:class=>'form'} do |f| %>
<div class="form-group">
	<%= f.input :name, :input_html => {:class=>"form-control"} %>
</div>

<div class="form-group">
	<%= f.input :description, :input_html => {:class=>"form-control"} %>
</div>
<hr class='hr-normal'>
<div class='row'>
	<div class='col-sm-12'>
		<%= button_tag(type: :submit, :class=>'btn btn-success btn-lg col-sm-12') do %>
		<i class="icon-save"></i> Salvar
		<% end %>
	</div>
</div>
<% end %>

app/views/classifications/create.js.erb
<% if @classification.errors.full_messages.any? %>
	$(".errors").html("");
	<% @classification.errors.full_messages.each do |full_message| %>
		$(".errors").append("<%= full_message %>")
	<% end %>
<% else %>
	bootbox.hideAll();
	$(".notice").html("")
	$(".notice").show();
	$(".notice").html("<%= flash[:notice] %>");
	$(".notice").addClass("alert-success");
	$("table tbody").append("<tr id='<%= @classification.id%>'><%= escape_javascript(render 'classification_row', :classification=> @classification) %></tr>");
<% end %>

app/views/classifications/edit.js.erb
bootbox.dialog({
	title: "<i class='icon-edit'></i> Editar quarto",
	message: "<%= escape_javascript(render 'form') %>"
})

app/views/classifications/index.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>
    <div class='row'>
      <div class='col-sm-12'>
        <div class='page-header'>
          <h1 class='pull-left'>
            <i class='icon-list'></i>
            <span>Tipos de Quartos</span>
          </h1>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="row">


<div class="row">
  <div class='col-sm-12'>

    <div class="notice alert alert-dismissable" style="display:none"></div>
    <div class="box bordered-box green-border" style="margin-bottom:0;">
      <div class="box-header blue-background">
        <div class="title">
          <i class="icon-user"></i> Lista de Tipos de Quarto
        </div>
        <div class="actions">
          <%= link_to new_classification_path, :remote =>true, :class=>'btn btn-success' do %>
          <i class="icon-plus"></i> Cadastrar tipo de quarto
          <% end %>
        </div>
      </div>
      <div class="box-content box-no-padding" style="margin-bottom:0;">
        <div class="responsive-table">
          <table class="table table-striped" style="margin-bottom:0;">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Descrição</th>
                <th></th>
              </tr>
            </thead>


            <tbody>
              <% @classifications.each do |classification| %>
              <tr id="classification-row-<%= classification.id %>">
                <%= render 'classification_row', :classification => classification %>
              </tr>
              <% end %>
            </tbody>
          </table>
          
        </div>
        <%= will_paginate @classifications, renderer: BootstrapPagination::Rails %>
      </div>

    </div>

  </div>
</div>

app/views/classifications/new.js.erb
bootbox.dialog({
	title: "Cadastrar tipos de quarto",
	message: "<%= escape_javascript(render 'form') %>"
});

app/views/classifications/show.html.erb
<div class="row">

  <div class="col-xs-12">
    <div id="orders">
      <div class="row">
        <div class="col-sm-12">
          <div class="page-header">
            <h1 class="pull-left">
              <i class="icon-inbox"></i>
              <span>Orders</span>
            </h1>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="box">
                <div class="box-content">
                  <% Classification.all.each do |classification| %>
                  <%= link_to new_booking_path(:classification_id => classification.id), :class => "btn box-content box-statistic green-background", remote: true  do %>
                  <h3 class='title text-error'><%= classification.name %></h3>
                  <% end %>
                  <% end %>

                </div>

                
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/classifications/update.js.erb
<% if @classification.errors.full_messages.any? %>
	<% @classification.errors.full_messages.each do |full_message| %>
		$(".errors").append("<%= full_message %>")
	<% end %>
<% else %>
	bootbox.hideAll();
	$(".notice").html("")
	$(".notice").show();
	$(".notice").addClass("alert-success");
	$(".notice").html("<%= flash[:notice] %>");
	$("tr#classification-row-<%= @classification.id %>").html("<%= escape_javascript(render 'classification_row', :classification=> @classification) %>");
<% end %>