config/routes.rb
Sample::Application.routes.draw do

	devise_for :users
	get "home/index"
	root :to => "home#index"
	resources :bookings, :customers, :products, :billings, :cashes, :expenses, :users

	resources :rooms do
		resources :bookings, :module => :rooms
	end

	resources :bookings do
		get 'choose_classification', on: :new
		get 'billing', on: :member
		post 'billing' => "bookings#create_billing", :as => "billings"
		resources :orders, :module => :bookings
	end

	resources :classifications do
		resources :pricings, :module => :classifications
		collection { post :import }
	end

	resource :user, only: [:edit] do
		collection do
			patch 'update_password'
		end
	end
end

app/models/room.rb
class Room < ActiveRecord::Base
	#@self.per_page = 5
	has_many :bookings 
	belongs_to :classification
	validates :number, :uniqueness => true, :presence => true

	scope :reserved_at_date, lambda{ |date = Time.now.at_midday| joins(:bookings).where("? BETWEEN bookings.start_at AND bookings.end_at", date) }
	scope :busy_at_date, lambda{ |date = Time.now.at_midday| joins(:bookings).where("? BETWEEN bookings.start_at AND bookings.end_at", date) }
	scope :free_at_date, lambda{ |date = Time.now.at_midday| where("id NOT IN (SELECT room_id FROM bookings WHERE (? between start_at and end_at))", date) }

	def vacant?
		!bookings.exists?(["(? BETWEEN start_at AND end_at)", Time.now])
	end

	def reserved?
		return bookings.where("(? BETWEEN start_at AND end_at) and bookings.hosted=?", Date.today, false).exists?
	end

	def busy?
		return bookings.where("(? BETWEEN start_at AND end_at) and bookings.hosted=?", Date.today, true).exists?
	end

	def has_bookings_between_dates?(start_date, end_date)
		bookings.where(["(start_at BETWEEN :start_at AND :end_at OR end_at BETWEEN :start_at AND :end_at)", {:start_at=> start_date, :end_at=> end_date}]).exists?
	end 

	def has_bookings_at_dates?(start_at, end_at)
		return bookings.where("(? BETWEEN start_at AND end_at OR ? BETWEEN start_at AND end_at)", start_at,end_at).exists?
	end
end

app/controllers/rooms/bookings_controller.rb
class Rooms::BookingsController < ApplicationController
	before_action :set_room
	before_action :set_booking, only: [:show, :edit, :update, :destroy]
	def new
		@booking = @room.bookings.build(:start_at=>Date.today, :end_at=>Date.tomorrow)
	end

	def create
		@booking = @room.bookings.build(booking_params)
		@booking.hosted = true
		if @booking.save
			flash[:notice] = "Cadastrado com sucesso"
		else
			flash[:notice] = "Erro ao cadastrar hospedagem"
		end
	end

	def edit
	end

	private

	def set_room
		@room  = Room.find(params[:room_id])
	end

	def set_booking
		@booking = Booking.find(params[:id])
	end

	def booking_params
		params.require(:booking).permit(:start_at, :end_at, :customer_id, :lot_of_persons)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:destroy, :edit, :show, :update]
  load_and_authorize_resource param_method: :room_params

  def index
    @rooms = Room.paginate(:page => params[:page])
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      @rooms = Room.paginate(:page => params[:page])
      flash[:notice] = "Cadastrado com sucesso"
    end
  end

  def edit
  end

  def show
  end

  def destroy
    if @room.destroy
      @rooms = Room.paginate(:page => params[:page])
      # redirect_to rooms_path, :notice => "Quarto removido"
    end
  end

  def set_room
    @room = Room.find(params[:id])
  end

  private
   def room_params
   	 params.require(:room).permit(:number, :description, :classification_id)
   end
end

app/views/rooms/_form.html.erb
<div class="errors alert alert-danger" style="display:none"></div>
<%= simple_form_for @room, :html=>{:class=>:form}, :remote => true do |f| %>
<fieldset>
  <div class='col-sm-12'>
    <div class="form-group">
      <%= f.input :number, :input_html => {:class=>"form-control"} %>
    </div>
    <div class="form-group">
      <%= f.association :classification, :input_html => {:class=>"form-control"} %>
    </div>
  </div>
</fieldset>
<hr class='hr-normal'>

  <div class='row'>
    <div class='col-sm-12'>
      <%= button_tag :type => 'submit', :class=>'btn btn-success btn-lg col-sm-12'  do %>
      <i class='icon-save'></i>
      Cadastrar
      <% end %>
    </div>
  </div>

</div>
<p>
</p>
<% end %>

app/views/rooms/_new.html.erb
<div class='row' id='content-wrapper'>
	<div class='col-sm-12'>

		<div class='box bordered-box blue-border'>
			<div class='box-header blue-background'>
				<div class='title'>
					<i class='icon-plus'></i>
					Novo Quarto
				</div>
			</div>
			<div class='box-content	'>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/rooms/_room.html.erb
<div class='pull-left' id="room-row-#{room.id}">
	<p>
		<a href='#detail'>
			<strong>#<%= room.number %></strong>
			<%= room.description %>
		</a>
	</p>
	<p>
		<% if room.busy? %>
		<span class='label label-important'>Ocupado</span>
		<% end %>
		<% if room.reserved? %>
		<span class='label label-warning'>Reservado</span>
		<% end %>
		<% if room.vacant? %>
		<span class='label label-success'>Vago</span>
		<% end %>
	</p>
</div>
<div class="text-right pull-right">
	<p>
	<%= link_to room, method: :delete, data: {confirm: "Deseja realmente excluir este quarto?"}, :class=>'btn btn-danger removable', :remote => true do %>
		<i class="icon-trash"></i> 
		<% end %>
	</p>
</div>
<div class='clearfix'></div>

app/views/rooms/_room_current_situation.html.erb
<% if room.vacant? %>
<%= link_to new_room_booking_path(room), :remote => true, :class=>"box-content box-statistic green-background", :style=>"text-decoration: none" do %>
<h3 class="title text-error"># <%= room.number %>
	<%= room.classification.name %>
</h3>

<% end %>
<% else %>

<%= link_to edit_room_booking_path(room, room.bookings.today), :remote => true, :class=>"box-content box-statistic red-background", :style=>"text-decoration: none" do %>
<h3 class="title text-error"># <%= room.number %></h3>

<% end %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class='col-sm-12'>
	<div class='box'>
		<div class="box-header blue-background">
			<div class="title">
				<i class="icon-room"></i> Quartos
			</div>
			<div class="actions">
			<%= link_to new_room_path, :remote =>true, :class=>'btn btn-success' do %>
				<i class="icon-plus"></i> Novo Produto
				<% end %>

			</div>
		</div>
		<div class='box-content'>
			<div class="row">
				<% @rooms.each do |room| %>
				<div  id="room-<%= room.id %>">
					<%= render 'rooms/room_current_situation', :room => room %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/rooms/_statuses.html.erb
<%= link_to root_path, :class => "btn box-content box-statistic red-background" do %>
	<h3 class='title text-error'><%= Room.busy_at_date.size %></h3>
	<small>Ocupados</small>
	<div class='text-error icon-lock align-right'></div>
<% end %>

	<%= link_to root_path, :class => "btn box-content box-statistic orange-background" do %>
	<h3 class='title text-warning'><%= Room.reserved_at_date.size %></h3>
	<small>Reservados</small>
	<div class='text-warning icon-unlock align-right'></div>
	<% end %>
<%= link_to root_path, :class => "btn box-content box-statistic green-background" do %>
	<h3 class='title text-success'><%= Room.free_at_date.size %></h3>
	<small>Livres</small>
	<div class='text-success icon-ok align-right'></div>
<% end %>

app/views/rooms/create.js.erb
<% if @room.errors.full_messages.any? %>
	$(".errors").html("");
	$(".errors").show();
	<% @room.errors.full_messages.each do |full_message| %>
		$(".errors").append("<p><%= full_message %></p>");
	<% end %>
<% else %>
	bootbox.hideAll();
	$(".notice").show();
	$(".notice").addClass("alert alert-success");
	$("#rooms").html("<%= escape_javascript(render 'rooms', :rooms => @rooms) %>");
<% end %>

app/views/rooms/destroy.js.erb
$(".notice").show();
$(".notice").addClass("alert alert-info")
$(".notice").html("<%= flash[:notice] %>")
$(".box-content").html("<%= escape_javascript(render 'rooms', :rooms => @rooms) %>");

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>

app/views/rooms/edit.js.erb
bootbox.dialog({
	title: "<i class='icon-edit'></i> Editar quarto",
	message: "<%= escape_javascript(render 'form') %>"
})

app/views/rooms/index.html.erb
<div class='row'>
	<div class='col-xs-12'>
		<div class='row'>
			<div class='col-sm-12'>
				<div class='page-header'>
					<h1 class='pull-left'>
						<i class='icon-room icon-large'></i>
						<span>Quartos</span>
					</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class='col-sm-12'>
		<div class='row' id="rooms">
			<%= render 'rooms', :rooms => @rooms %>
		</div>
	</div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/new.js.erb
bootbox.dialog({
	title: "<i class='icon-plus'></i> Novo quarto",
	message: "<%= escape_javascript(render 'form') %>"
})

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>