config/routes.rb
Sample::Application.routes.draw do

	devise_for :users
	get "home/index"
	root :to => "home#index"
	resources :bookings, :customers, :products, :billings, :cashes, :expenses, :users

	resources :rooms do
		resources :bookings, :module => :rooms
	end

	resources :bookings do
		get 'choose_classification', on: :new
		get 'billing', on: :member
		post 'billing' => "bookings#create_billing", :as => "billings"
		resources :orders, :module => :bookings
	end

	resources :classifications do
		resources :pricings, :module => :classifications
		collection { post :import }
	end

	resource :user, only: [:edit] do
		collection do
			patch 'update_password'
		end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	self.per_page = 5
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit,:update, :show, :destroy]
  load_and_authorize_resource param_method: :product_params
  
  def index
     @products = Product.paginate(:page => params[:page])
  end

  def new
    @product = Product.new
  end

  def create
     @product = Product.new(product_params)
     if @product.save
        flash[:notice] = "Cadastrado com sucesso"
     end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
        flash[:notice] = "Editado com sucesso"
    end
  end

  def destroy
    if @product.destroy
        flash[:notice] = "Produto removido com sucesso"
    end
    
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
    
    def product_params
       product_params = params.require(:product).permit(:name, :price, :preco)
       product_params[:price] = product_params[:price].to_number 
       product_params
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html=>{:class=>:form}, :remote => true do |f| %>
<fieldset>
  <div class='col-sm-12'>
    <div class="form-group">
      <%= f.input :name,  :input_html => {:class => "form-control"} %>
    </div>
    <div class="input-group">
      <span class="input-group-addon">R$</span>
      <%= f.input :price, as: :currency, :label=> false, :input_html => {value: number_to_currency(f.object.price), :class => "form-control"} %>
    </div>
  </div>
</fieldset>
<hr class='hr-normal' />
<div class="actions">
  <div class='row'>
    <div class='col-sm-12'>
      <%= button_tag :type => 'submit', :class=>'btn btn-success btn-lg col-sm-12' do %>
      <i class='icon-save'></i> Salvar
      <% end %>
    </div>
  </div>
</div>
<% end %>
<script type="text/javascript">

  $(document).ready(function() {
    $("input[type=text].currency").setMask('decimal');
  });
</script>

app/views/products/_list.html.erb
	<div class='row' id='list'>
		<div class='col-sm-12'>
			<div class='box'>
				<div class='box-content'>
					<% @products.each do |product| %>
						<%= render product, :product => @product %>
					<% end %>
				</div>
			</div>
		</div>
	</div>

app/views/products/_product.html.erb
<div class='pull-left'>
	<p>
		<a href='#detail'>
			<strong>#<%= product.name %></strong>
			<p><%= product.price %></p>
		</a>
	</p>
</div>

<div class='clearfix'></div>

app/views/products/_product_row.html.erb
<td><%= product.name %></td>
<td><%= number_to_currency(product.price) %></td>

<td>
	<div class="text-right">
		
		<%= link_to edit_product_path(product), :remote => true, :class=>'btn btn-success btn-xs removable' do %>
		<i class="icon-edit"></i> Editar
		<% end %>
	</div>
</td>

app/views/products/create.js.erb
<% if @product.errors.full_messages.any? %>
	$(".errors").show();
	<%= @product.errors.full_messages.each do |full_message| %>
		$(".errors").append("<p><%= full_message %></p>");
	<% end %>
<% else %>
	bootbox.hideAll();
	$(".notice").html("");
	$(".notice").show();
	$(".notice").addClass("alert alert-success");
	$(".notice").append("<%= flash[:notice] %>");
	$('table tbody').append('<tr id="product-row-<%= @product.id %>"><%= escape_javascript(render "product_row", :product => @product) %></tr>');
<% end %>

app/views/products/destroy.js.erb
$('.removable').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  
$(".notice").show();
$(".notice").addClass("alert alert-info")
$(".notice").html("<%= flash[:notice] %>")

app/views/products/edit.js.erb
bootbox.dialog({
	message: '<%= escape_javascript(render "form") %>'
})

app/views/products/index.html.erb
<div class='row' id='content-wrapper'>
  <div class='col-xs-12'>
    <div class='row'>
      <div class='col-sm-12'>
        <div class='page-header'>
          <h1 class='pull-left'>
            <i class="icon-shopping-cart"></i>
            <span>Produtos</span>
          </h1>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class='col-sm-12'>

    <div class="notice alert alert-dismissable" style="display:none"></div>
    <div class="box bordered-box green-border" style="margin-bottom:0;">
      <div class="box-header blue-background">
        <div class="title">
      		<i class="icon-list"></i> Lista de Produtos
        	</div>
        <div class="actions">
          <%= link_to new_product_path, :remote =>true, :class=>'btn btn-success' do %>
            <i class="icon-plus"></i> Novo Produto
          <% end %>

        </div>
      </div>
      <div class="box-content box-no-padding" style="margin-bottom:0;">
        <div class="responsive-table">
          <table class="table table-striped" style="margin-bottom:0;">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Preço</th>
                <th></th>
              </tr>
            </thead>

              
            <tbody>
              <% @products.each do |product| %>
                <tr id="product-row-<%= product.id %>">
                	<%= render 'product_row', :product => product %>
                </tr>
              <% end %>
            </tbody>
          </table>
          
        </div>
        <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
      </div>

    </div>

  </div>
</div>

app/views/products/new.js.erb
bootbox.dialog({
	message: "<%= escape_javascript(render 'form') %>"
});

app/views/products/update.js.erb
$(".notice").show();
<% if @product.errors.full_messages.any? %>
	<%= @product.errors.full_messages.each do |full_message| %>
		$(".notice").append("<%= full_message %>");
	<% end %>
<% else %>
	bootbox.hideAll();
	$(".notice").addClass("alert alert-success");
	$(".notice").append("<%= flash[:notice] %>");
	$('tr#product-row-<%= @product.id %>').html('<%= escape_javascript(render "product_row", :product => @product) %>');
<% end %>